- name: kubeadm join
  command: "kubeadm join  --discovery-token-unsafe-skip-ca-verification --token {{ hostvars[groups.master[0]]['token'].stdout }} {{ hostvars[groups.master[0]]['ansible_default_ipv4']['address'] }}:6443"
  args:
    creates: /etc/kubernetes/kubelet.conf
